"use client"
import Footer from "../../components/Footer";
import Nav from "../../components/Nav"
import { SessionProvider } from "next-auth/react";
import { QueryClientProvider, QueryClient } from "@tanstack/react-query";
import Meta from "../../components/Head";
import { JSX, useState } from "react";
import "../../styles/globals.css"

// export const metadata = {
//     title: 'Next.js',
//     description: 'Generated by Next.js',
// }

export default function RootLayout({ children }): JSX.Element {
    const [queryclient] = useState(() => new QueryClient());
    return (
        <QueryClientProvider client={queryclient}>
            <html lang="en">
                <SessionProvider>
                {/* <Meta name="Crypto" /> */}
                {/* {width >= 700 ? <Nav /> : !show && <VscListFlat className="open" onClick={() => setShow(prevValue => !prevValue)} />}
                    {width <= 700 && <SideBar show={show} setShow={setShow} />} */}
                <body>
                    <Nav />
                    {children}
                    <Footer />
                </body>
                </SessionProvider>
            </html>
        </QueryClientProvider>
    )
}